export const upcomingEvents = [
  {
    id: "1",
    title: "Bathukamma Celebrations 2026",
    description: "Join us for the vibrant Bathukamma flower festival celebrating Telangana's rich cultural heritage with music, dance, and traditional festivities.",
    date: "2026-10-10",
    time: "4:00 PM - 9:00 PM",
    location: "Bellevue Community Center, WA",
    image: "/placeholder.svg",
    isFree: false,
    ticketPrice: 25,
    status: "upcoming" as const,
  },
  {
    id: "2",
    title: "Ugadi & Sri Rama Navami",
    description: "Celebrate Telugu New Year with traditional Ugadi Pachadi, cultural performances, and community feast.",
    date: "2026-04-05",
    time: "10:00 AM - 3:00 PM",
    location: "Redmond Senior Center, WA",
    image: "/placeholder.svg",
    isFree: true,
    ticketPrice: 0,
    status: "upcoming" as const,
  },
  {
    id: "3",
    title: "Annual Summer Picnic",
    description: "Bring your family for a fun-filled day at the park with games, food, and great company.",
    date: "2026-07-18",
    time: "11:00 AM - 5:00 PM",
    location: "Marymoor Park, Redmond, WA",
    image: "/placeholder.svg",
    isFree: true,
    ticketPrice: 0,
    status: "upcoming" as const,
  },
];

export const pastEvents = [
  {
    id: "4",
    title: "Bonalu Festival 2025",
    description: "A grand celebration of the traditional Bonalu festival with pot decorations and cultural dances.",
    date: "2025-07-20",
    time: "3:00 PM - 8:00 PM",
    location: "Kent Community Center, WA",
    image: "/placeholder.svg",
    isFree: false,
    ticketPrice: 20,
    status: "past" as const,
  },
  {
    id: "5",
    title: "Diwali Gala 2025",
    description: "An evening of lights, music, and celebration with the Telangana community.",
    date: "2025-11-01",
    time: "6:00 PM - 11:00 PM",
    location: "Meydenbauer Center, Bellevue, WA",
    image: "/placeholder.svg",
    isFree: false,
    ticketPrice: 35,
    status: "past" as const,
  },
  {
    id: "6",
    title: "Republic Day Celebrations 2025",
    description: "Patriotic performances and cultural showcase marking India's Republic Day.",
    date: "2025-01-26",
    time: "10:00 AM - 2:00 PM",
    location: "Kirkland Performance Center, WA",
    image: "/placeholder.svg",
    isFree: true,
    ticketPrice: 0,
    status: "past" as const,
  },
];

export const announcements = [
  {
    id: "1",
    title: "Membership Drive 2026",
    content: "Join ATA Seattle today and become part of the largest Telangana community in the Pacific Northwest. Special early-bird pricing available until March 31st!",
    publishedAt: "2026-03-01",
  },
  {
    id: "2",
    title: "Volunteer Opportunities",
    content: "We're looking for dedicated volunteers to help organize our upcoming Bathukamma celebrations. Sign up now!",
    publishedAt: "2026-03-10",
  },
  {
    id: "3",
    title: "Scholarship Applications Open",
    content: "ATA Seattle is offering scholarships for Telugu students excelling in academics and community service. Apply by April 15th.",
    publishedAt: "2026-02-20",
  },
];

export const membershipTiers = [
  {
    id: "1",
    name: "Individual",
    price: 50,
    duration: "1 year",
    benefits: [
      "Access to all free events",
      "Discounted tickets for paid events",
      "Monthly newsletter",
      "Voting rights in annual elections",
      "Community directory listing",
    ],
  },
  {
    id: "2",
    name: "Family",
    price: 100,
    duration: "1 year",
    benefits: [
      "All Individual benefits",
      "Covers up to 4 family members",
      "Priority event registration",
      "Family photo in annual directory",
      "Kids program access",
      "Festival kit included",
    ],
    popular: true,
  },
  {
    id: "3",
    name: "Lifetime",
    price: 500,
    duration: "Lifetime",
    benefits: [
      "All Family benefits forever",
      "VIP seating at all events",
      "Lifetime recognition on website",
      "Exclusive lifetime member gatherings",
      "Complimentary event tickets (2/year)",
      "Legacy membership for next generation",
    ],
  },
];

export const leadershipTeam = [
  { id: "1", name: "Rajesh Kumar", title: "President", photo: "/placeholder.svg", order: 1 },
  { id: "2", name: "Priya Reddy", title: "Vice President", photo: "/placeholder.svg", order: 2 },
  { id: "3", name: "Suresh Rao", title: "Secretary", photo: "/placeholder.svg", order: 3 },
  { id: "4", name: "Lakshmi Devi", title: "Treasurer", photo: "/placeholder.svg", order: 4 },
  { id: "5", name: "Venkat Naidu", title: "Cultural Secretary", photo: "/placeholder.svg", order: 5 },
  { id: "6", name: "Anitha Sharma", title: "Membership Chair", photo: "/placeholder.svg", order: 6 },
  { id: "7", name: "Ravi Teja", title: "Events Coordinator", photo: "/placeholder.svg", order: 7 },
  { id: "8", name: "Deepa Rani", title: "Communications Lead", photo: "/placeholder.svg", order: 8 },
];
